typedef struct { int wall;} room_t;
void clear_maze();
int is_wall(int x, int j);
void build_wall(int x, int j);
void clear_wall(int x, int j);
void build_treasure(int x, int j);
void build_monster(int x, int j);
void set_location_x(int x);
int get_location_x();
void print_maze();
void move_right();
void move_left();
void move_up();
void move_down();
void set_location_y(int x);
int  get_location_y();
void add_sword();
void clear_sword();
int have_sword();
void build_sword(int i, int j);
